-- Add new columns to employees table (DOB, bank, PAN, PF, UAN, LOP tracking)

ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS date_of_birth DATE,
  ADD COLUMN IF NOT EXISTS bank_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS bank_account_no TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS pan_no TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS location TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS pf_no TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS universal_account_number TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS original_hire_date DATE,
  ADD COLUMN IF NOT EXISTS total_days NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lop NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS llop NUMERIC DEFAULT 0;

