-- ============ ADD GPS GEO-LOCATION COLUMNS TO ATTENDANCE ============
ALTER TABLE public.attendance
  ADD COLUMN IF NOT EXISTS latitude NUMERIC,
  ADD COLUMN IF NOT EXISTS longitude NUMERIC,
  ADD COLUMN IF NOT EXISTS accuracy NUMERIC,
  ADD COLUMN IF NOT EXISTS distance_meters NUMERIC;
