-- Add hour-based payroll columns for attendance-driven salary calculations
ALTER TABLE public.payroll
  ADD COLUMN IF NOT EXISTS "standardWorkingDays" INTEGER NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS "standardWorkingHours" INTEGER NOT NULL DEFAULT 9,
  ADD COLUMN IF NOT EXISTS "hourlyRate" NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "totalWorkedHours" NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "overtimeHours" NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "grossSalary" NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "overtimeMultiplier" NUMERIC NOT NULL DEFAULT 1.5;

DROP VIEW IF EXISTS public.payroll_with_employee_details;
CREATE VIEW public.payroll_with_employee_details AS
SELECT 
  p.id,
  p.user_auth_uid,
  p.month,
  p.year,
  p."basicSalary",
  p."monthlySalary",
  p."yearlySalary",
  p."workingDays",
  p."presentDays",
  p."absentDays",
  p."approvedLeaves",
  p.holidays,
  p.deductions,
  p."netSalary",
  p.hra,
  p."otherAllowances",
  p."yearlyBasic",
  p."yearlyHra",
  p."yearlyOtherAllowances",
  p."standardWorkingDays",
  p."standardWorkingHours",
  p."hourlyRate",
  p."totalWorkedHours",
  p."overtimeHours",
  p."grossSalary",
  p."overtimeMultiplier",
  p.status,
  p.created_at,
  p.updated_at,
  e.name,
  e.employee_id,
  e.email,
  e.department,
  e.designation,
  e.salary,
  e."joiningDate",
  e.phone,
  e.bank_name,
  e.bank_account_no,
  e.pan_no,
  e.location,
  e.pf_no,
  e.universal_account_number,
  e.date_of_birth
FROM public.payroll p
JOIN public.employees e ON p.user_auth_uid = e.auth_uid;
